GET http://localhost:3000/api/saludo/andres HTTP/1.1

###

GET http://localhost:3000/api/users/Matias HTTP/1.1

###

GET http://localhost:3000/api/users/Santiago HTTP/1.1


### 

POST http://localhost:3000/api/users/add HTTP/1.1
Authorization: Admin
Content-Type: application/json

{
    "name": "Tomi",
    "position": "Admin"
}

###

DELETE http://localhost:3000/api/kill/6 HTTP/1.1
Authorization: Admin

###

PUT http://localhost:3000/api/change/Andres HTTP/1.1
Content-Type: application/json

{
    "name": "Matias",
    "position": "Admin"
}

### 

GET http://localhost:3000/api/usuarios HTTP/1.1

###

GET http://localhost:3000/api/users/usuario/user HTTP/1.1
